name: bff-v2-production

on:
  pull_request:
    branches:
      - production
    paths:
      - "apps/bff/**"
      - ".github/workflows/bff-production.yml"
  push:
    branches:
      - production
    tags:
      - "v*"
    paths:
      - "apps/bff/**"
      - ".github/workflows/bff-production.yml"
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  packages: write
  security-events: write

concurrency:
  group: bff-v2-production-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bff_prd:
    environment: ${{ vars.PIPELINE_ENV_PRD || 'prd' }}
    uses: aviait/deploy-templates/.github/workflows/v2-bff.yml@main
    with:
      environment: ${{ vars.PIPELINE_ENV_PRD || 'prd' }}
      working_directory: apps/bff
      node_version: ${{ vars.BFF_NODE_VERSION || '20' }}
      package_manager: ${{ vars.BFF_PACKAGE_MANAGER || 'pnpm' }}
      pnpm_version: ${{ vars.BFF_PNPM_VERSION || '9' }}
      cache_dependency_path: ${{ vars.BFF_CACHE_DEPENDENCY_PATH || 'apps/bff/pnpm-lock.yaml' }}
      lint_cmd: ${{ vars.BFF_LINT_CMD || 'npm run lint' }}
      typecheck_cmd: ${{ vars.BFF_TYPECHECK_CMD || 'npm run typecheck' }}
      test_cmd: ${{ vars.BFF_TEST_CMD || 'npm test -- --ci' }}
      dockerfile: ${{ vars.BFF_DOCKERFILE || 'Dockerfile' }}
      registry: ${{ vars.BFF_REGISTRY || 'ghcr.io' }}
      image_namespace: ${{ vars.BFF_IMAGE_NAMESPACE }}
      image_name: ${{ vars.BFF_IMAGE_NAME || format('{0}/bff', github.repository) }}
      semver_prefix: ${{ vars.PIPELINE_SEMVER_PREFIX || 'v' }}
      enable_release: true
      deploy_on_tag_only: ${{ vars.PIPELINE_ENABLE_PROD_FROM_BRANCH != 'true' }}
      inject_all_github_vars: ${{ vars.BFF_INJECT_ALL_GITHUB_VARS != 'false' }}
      github_vars_prefix: ${{ vars.BFF_GITHUB_VARS_PREFIX }}
      github_vars_exclude: ${{ vars.BFF_GITHUB_VARS_EXCLUDE }}
    secrets:
      PEM_KEY: ${{ secrets.PEM_KEY }}
      DEPLOY_REGISTRY_USERNAME: ${{ secrets.DEPLOY_REGISTRY_USERNAME }}
      DEPLOY_REGISTRY_PASSWORD: ${{ secrets.DEPLOY_REGISTRY_PASSWORD }}
      DOCKER_RUN_ENVS_FILE: ${{ secrets.DOCKER_RUN_ENVS_FILE }}
