name: web-v2-production

on:
  pull_request:
    branches:
      - production
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "yarn.lock"
      - "tsconfig*.json"
      - "vite.config.ts"
      - "vitest.config.ts"
      - "eslint.config.mjs"
      - "index.html"
      - ".env.example"
      - ".github/workflows/web-production.yml"
  push:
    branches:
      - production
    tags:
      - "*"
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "yarn.lock"
      - "tsconfig*.json"
      - "vite.config.ts"
      - "vitest.config.ts"
      - "eslint.config.mjs"
      - "index.html"
      - ".env.example"
      - ".github/workflows/web-production.yml"
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  security-events: write

concurrency:
  group: web-v2-production-${{ github.ref }}
  cancel-in-progress: false

jobs:
  web_prd:
    if: ${{ !startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, format('refs/tags/{0}', vars.PIPELINE_SEMVER_PREFIX != '' && vars.PIPELINE_SEMVER_PREFIX || 'v')) }}
    permissions:
      contents: write
      actions: read
      security-events: write
    uses: aviait/deploy-templates/.github/workflows/v2-web.yml@main
    with:
      environment: ${{ vars.PIPELINE_ENV_PRD || 'prd' }}
      working_directory: ${{ vars.WEB_WORKING_DIRECTORY || '.' }}
      node_version: ${{ vars.WEB_NODE_VERSION || '20' }}
      package_manager: ${{ vars.WEB_PACKAGE_MANAGER || 'yarn' }}
      pnpm_version: ${{ vars.WEB_PNPM_VERSION || '9' }}
      cache_dependency_path: ${{ vars.WEB_CACHE_DEPENDENCY_PATH || 'yarn.lock' }}
      lint_cmd: ${{ vars.WEB_LINT_CMD || 'yarn lint' }}
      typecheck_cmd: ${{ vars.WEB_TYPECHECK_CMD || 'yarn typecheck' }}
      test_cmd: ${{ vars.WEB_TEST_CMD || 'yarn test' }}
      build_cmd: ${{ vars.WEB_BUILD_CMD || 'yarn build' }}
      build_output_dir: ${{ vars.WEB_BUILD_OUTPUT_DIR || 'build' }}
      artifact_name: ${{ vars.WEB_ARTIFACT_NAME || 'web-build' }}
      dns_name: ${{ vars.WEB_DNS || vars.DNS_NAME }}
      semver_prefix: ${{ vars.PIPELINE_SEMVER_PREFIX || 'v' }}
      enable_release: true
      deploy_on_tag_only: ${{ vars.PIPELINE_ENABLE_PROD_FROM_BRANCH != 'true' }}
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
      PEM_KEY: ${{ secrets.PEM_KEY }}
